### ISSUE TITLE
When I change the  "video-filter=croppadd:scene" in "startStream.bat" , it dosen't work.

### ISSUE THREAD

**Issue by abramyangCN** [tomekceszke/traffic-light-detection#1]
![image](https://user-images.githubusercontent.com/19504192/53684254-1290df00-3d46-11e9-8d89-d2bfdc20dae6.png)
how I can fix the problem?
thanks! :）

**Comment by tomekceszke** [comment]
What kind of change do you mean? 
Those filters are needed to continuously crop and save single frame as png file (`scene.png`) from the stream. 
Then that png is parsed and analyzed by `detect` script. 
If you remove or change those VLC filteres then my script won't be able to detect current light due to lack of input.

**Comment by tomekceszke** [comment]
Issue fixed.
